"""Algo Lab Trade Candidate and Order Intent Contracts.

Decouples Strategy Alpha Generation from Portfolio Risk and Execution Simulation.
Pipeline:
Strategy -> TradeCandidate -> Risk/Constraint Check -> SimulatedOrder -> SimulatedFill
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, Optional
import uuid
from pydantic import BaseModel, Field

from services.backtest_engine.contracts import OrderSide, OrderType


class CandidateAction(str, Enum):
    ENTER_LONG = "ENTER_LONG"
    ENTER_SHORT = "ENTER_SHORT"
    EXIT_LONG = "EXIT_LONG"
    EXIT_SHORT = "EXIT_SHORT"
    HOLD = "HOLD"
    WAIT = "WAIT"


class TradeCandidate(BaseModel):
    """Candidate trade proposal generated by a Strategy point-in-time."""

    candidate_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    strategy_id: str
    strategy_version: str
    symbol: str
    timestamp: datetime
    action: CandidateAction
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence score based on evidence confluence")
    reason: str = Field(..., description="Explainable reason citing evidence")
    evidence: Dict[str, Any] = Field(default_factory=dict)

    # Risk parameters suggested by strategy
    suggested_limit_price: Optional[float] = None
    suggested_stop_loss: Optional[float] = None
    suggested_target_price: Optional[float] = None
    suggested_position_size_pct: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    time_in_force_bars: int = 1  # Valid for N bars before expiration


class SimulatedOrder(BaseModel):
    """Internal order generated after risk and position constraint approval."""

    order_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    candidate_id: str
    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: int = Field(gt=0)
    created_at: datetime
    limit_price: Optional[float] = None
    stop_loss: Optional[float] = None
    target_price: Optional[float] = None
    is_exit_order: bool = False
    exit_reason: Optional[str] = None


class SimulatedFill(BaseModel):
    """Simulated execution fill with realistic cost and slippage attribution."""

    fill_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    order_id: str
    candidate_id: str
    symbol: str
    side: OrderSide
    quantity: int
    fill_price: float
    slippage: float
    fees: float
    timestamp: datetime
    is_exit: bool = False
    exit_reason: Optional[str] = None
